version: "3.9"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  chrome_79:
    image: selenium/node-chrome-debug:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  firefox:
    image: selenium/node-firefox-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
