package com.girijaAutomation.Enum;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOT,
    FAILEDSTEPSSCREENSHOT,
    SKIPPEDSTEPSSCREENSHOT,
    RETRYFAILEDTESTS,
    RUNMODE,
    BROWSER;
}
